/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'dateLabel' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addNotification' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'deleteNotification' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'editNotification' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'dateLabel' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addNotification' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteNotification' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'editNotification' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };